-- OurStory production schema for Supabase Postgres.
-- Run this in the Supabase SQL editor after creating the project.

create extension if not exists "pgcrypto";

create type public.couple_role as enum ('owner', 'partner');
create type public.game_type as enum ('question_jar', 'memory_lane', 'date_spark', 'love_awards');
create type public.session_status as enum ('draft', 'active', 'revealed', 'archived');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.couples (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Our Story',
  invite_code text not null unique default upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 10)),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.couple_members (
  couple_id uuid not null references public.couples(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.couple_role not null default 'partner',
  joined_at timestamptz not null default now(),
  primary key (couple_id, user_id)
);

create table public.questions (
  id bigint generated by default as identity primary key,
  category text not null,
  mood text not null,
  prompt text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  game_type public.game_type not null,
  status public.session_status not null default 'draft',
  title text,
  metadata jsonb not null default '{}'::jsonb,
  current_question_id bigint references public.questions(id),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  revealed_at timestamptz,
  archived_at timestamptz
);

create table public.answers (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  question_id bigint references public.questions(id),
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, user_id)
);

create table public.memories (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  title text not null,
  body text,
  happened_on date,
  emotion text,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.date_ideas (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  title text not null,
  description text not null,
  budget text,
  energy text,
  scheduled_for timestamptz,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.awards (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  note text not null,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch_updated_at before update on public.profiles for each row execute function public.touch_updated_at();
create trigger couples_touch_updated_at before update on public.couples for each row execute function public.touch_updated_at();
create trigger answers_touch_updated_at before update on public.answers for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)), new.raw_user_meta_data ->> 'avatar_url')
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();


create or replace function public.handle_new_couple()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.couple_members (couple_id, user_id, role)
  values (new.id, new.created_by, 'owner')
  on conflict (couple_id, user_id) do nothing;
  return new;
end;
$$;

create trigger on_couple_created after insert on public.couples for each row execute function public.handle_new_couple();

alter table public.profiles enable row level security;
alter table public.couples enable row level security;
alter table public.couple_members enable row level security;
alter table public.questions enable row level security;
alter table public.game_sessions enable row level security;
alter table public.answers enable row level security;
alter table public.memories enable row level security;
alter table public.date_ideas enable row level security;
alter table public.awards enable row level security;


create or replace function public.is_couple_member(target_couple_id uuid, target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.couple_members cm
    where cm.couple_id = target_couple_id
      and cm.user_id = target_user_id
  );
$$;

create or replace function public.is_couple_owner(target_couple_id uuid, target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.couple_members cm
    where cm.couple_id = target_couple_id
      and cm.user_id = target_user_id
      and cm.role = 'owner'
  );
$$;


create or replace function public.can_access_session(target_session_id uuid, target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.game_sessions gs
    join public.couple_members cm on cm.couple_id = gs.couple_id
    where gs.id = target_session_id
      and cm.user_id = target_user_id
  );
$$;

create policy "Profiles are visible to their owner" on public.profiles for select using (auth.uid() = id);
create policy "Profiles can update themselves" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Questions are readable by authenticated users" on public.questions for select to authenticated using (is_active = true);

create policy "Couple members can read their couples" on public.couples for select using (public.is_couple_member(id));
create policy "Authenticated users can create couples" on public.couples for insert to authenticated with check (created_by = auth.uid());
create policy "Couple owners can update couples" on public.couples for update using (public.is_couple_owner(id));

create policy "Members can read memberships" on public.couple_members for select using (public.is_couple_member(couple_id));
create policy "Users can join themselves" on public.couple_members for insert to authenticated with check (user_id = auth.uid());

create policy "Members can manage sessions" on public.game_sessions for all using (public.is_couple_member(couple_id)) with check (public.is_couple_member(couple_id));
create policy "Members can manage answers" on public.answers for all using (public.can_access_session(session_id)) with check (user_id = auth.uid());
create policy "Members can manage memories" on public.memories for all using (public.is_couple_member(couple_id)) with check (public.is_couple_member(couple_id));
create policy "Members can manage date ideas" on public.date_ideas for all using (public.is_couple_member(couple_id)) with check (public.is_couple_member(couple_id));
create policy "Members can manage awards" on public.awards for all using (public.is_couple_member(couple_id)) with check (public.is_couple_member(couple_id));
