-- Seed 100 original OurStory question prompts.
insert into public.questions (category, mood, prompt) values
  ('connection', 'tender', 'What everyday sound or habit of ours feels most like home to you?'),
  ('connection', 'tender', 'When did you first feel truly seen by me?'),
  ('connection', 'tender', 'What tiny kindness from me has stayed with you longer than I realized?'),
  ('connection', 'tender', 'Which ordinary moment from this week would you like to replay?'),
  ('connection', 'tender', 'What part of our relationship helps you breathe easier?'),
  ('connection', 'tender', 'How can I make your mornings feel more supported?'),
  ('connection', 'tender', 'What is one thing I do that makes our space feel safe?'),
  ('connection', 'tender', 'Where do you feel most connected to me: talking, laughing, planning, touching, or resting?'),
  ('connection', 'tender', 'What unspoken ritual between us means the most to you?'),
  ('connection', 'tender', 'What would make our next goodbye feel softer?'),
  ('memories', 'nostalgic', 'What is a first from our story that still feels vivid?'),
  ('memories', 'nostalgic', 'Which photo of us deserves a better caption?'),
  ('memories', 'nostalgic', 'What meal, snack, or drink reminds you of us?'),
  ('memories', 'nostalgic', 'What place changed meaning after we experienced it together?'),
  ('memories', 'nostalgic', 'Which laugh between us do you wish we could bottle?'),
  ('memories', 'nostalgic', 'What song belongs in the opening scene of our relationship movie?'),
  ('memories', 'nostalgic', 'What detail from our early days do you hope we never forget?'),
  ('memories', 'nostalgic', 'Which challenge did we handle better together than you expected?'),
  ('memories', 'nostalgic', 'What is a moment when you felt proud to be with me?'),
  ('memories', 'nostalgic', 'What memory should we turn into an annual tradition?'),
  ('future', 'hopeful', 'What is one dream you want us to protect from busyness?'),
  ('future', 'hopeful', 'How do you imagine our ideal slow Sunday one year from now?'),
  ('future', 'hopeful', 'What should we learn together next?'),
  ('future', 'hopeful', 'What kind of home energy do you want us to build?'),
  ('future', 'hopeful', 'Where should our next small adventure take us?'),
  ('future', 'hopeful', 'What is one shared goal that would make us feel closer?'),
  ('future', 'hopeful', 'How can we celebrate progress before everything is perfect?'),
  ('future', 'hopeful', 'What future version of us would you love to meet?'),
  ('future', 'hopeful', 'What habit would help us become the couple we want to be?'),
  ('future', 'hopeful', 'What promise should we renew in a practical way this month?'),
  ('play', 'playful', 'If our relationship had a mascot, what would it be and why?'),
  ('play', 'playful', 'What ridiculous award would you give me this week?'),
  ('play', 'playful', 'What should be the title of our next date-night episode?'),
  ('play', 'playful', 'Which one of us would survive better in a cozy cabin mystery?'),
  ('play', 'playful', 'What is my most lovable nonsense habit?'),
  ('play', 'playful', 'If we opened a tiny business together, what would we sell?'),
  ('play', 'playful', 'What fictional world should we vacation in for a weekend?'),
  ('play', 'playful', 'Which inside joke deserves its own holiday?'),
  ('play', 'playful', 'What silly rule would improve our home for one day?'),
  ('play', 'playful', 'If our love had a flavor, what would it taste like?'),
  ('intimacy', 'deep', 'What fear feels easier to carry when you tell me about it?'),
  ('intimacy', 'deep', 'When do you need reassurance but struggle to ask for it?'),
  ('intimacy', 'deep', 'What does emotional safety look like for you during conflict?'),
  ('intimacy', 'deep', 'What part of your inner world do you want me to understand better?'),
  ('intimacy', 'deep', 'How can I listen in a way that helps you feel less alone?'),
  ('intimacy', 'deep', 'What tenderness do you wish we made more time for?'),
  ('intimacy', 'deep', 'What boundary would help you feel more respected and loved?'),
  ('intimacy', 'deep', 'What is something you are healing that I can honor gently?'),
  ('intimacy', 'deep', 'How do you know when I am fully present with you?'),
  ('intimacy', 'deep', 'What truth about love has our relationship taught you?'),
  ('gratitude', 'warm', 'What are three things you appreciated about me recently?'),
  ('gratitude', 'warm', 'What effort of mine do you want to acknowledge today?'),
  ('gratitude', 'warm', 'What quality in me makes your life brighter?'),
  ('gratitude', 'warm', 'What have we built that you are thankful for?'),
  ('gratitude', 'warm', 'What is something I handled with care that mattered to you?'),
  ('gratitude', 'warm', 'What does my love make possible for you?'),
  ('gratitude', 'warm', 'What moment today made you feel lucky about us?'),
  ('gratitude', 'warm', 'What strength do you see in me that I sometimes miss?'),
  ('gratitude', 'warm', 'What comfort do I bring without trying?'),
  ('gratitude', 'warm', 'What should we thank past-us for doing?'),
  ('conflict', 'grounded', 'What helps you come back to me after tension?'),
  ('conflict', 'grounded', 'What repair phrase would feel good for us to use more often?'),
  ('conflict', 'grounded', 'How can we disagree without making either person feel alone?'),
  ('conflict', 'grounded', 'What signal could mean we need a pause instead of more words?'),
  ('conflict', 'grounded', 'What assumption should I avoid making about you during stress?'),
  ('conflict', 'grounded', 'What is one pattern we are ready to outgrow together?'),
  ('conflict', 'grounded', 'What does a sincere apology sound like to you?'),
  ('conflict', 'grounded', 'What helps you feel safe enough to be honest?'),
  ('conflict', 'grounded', 'What can we do after hard conversations to reconnect?'),
  ('conflict', 'grounded', 'What would make our next conflict more respectful than the last?'),
  ('dates', 'romantic', 'What simple date would feel luxurious to you right now?'),
  ('dates', 'romantic', 'What is a low-budget plan that would still feel special?'),
  ('dates', 'romantic', 'What place nearby have we overlooked for too long?'),
  ('dates', 'romantic', 'What should our rainy-day date include?'),
  ('dates', 'romantic', 'What would make a stay-at-home evening feel intentional?'),
  ('dates', 'romantic', 'What kind of surprise would delight you without overwhelming you?'),
  ('dates', 'romantic', 'What food should anchor our next date?'),
  ('dates', 'romantic', 'What errand could become a mini-adventure if we did it together?'),
  ('dates', 'romantic', 'What should we do when we only have thirty minutes?'),
  ('dates', 'romantic', 'What date idea matches our current season of life?'),
  ('growth', 'curious', 'What have you learned about yourself through loving me?'),
  ('growth', 'curious', 'What skill do you think we are developing as a couple?'),
  ('growth', 'curious', 'Where have you noticed us becoming gentler?'),
  ('growth', 'curious', 'What new language of love are you learning from me?'),
  ('growth', 'curious', 'What is one question you wish I asked you more often?'),
  ('growth', 'curious', 'What part of our relationship feels stronger than it did before?'),
  ('growth', 'curious', 'What would help us stay curious instead of assuming?'),
  ('growth', 'curious', 'What have we learned from a plan that did not work out?'),
  ('growth', 'curious', 'What personal win should we celebrate together?'),
  ('growth', 'curious', 'What is one way we can support each other without fixing everything?'),
  ('spicy', 'flirty', 'What compliment from me would you like to hear more often?'),
  ('spicy', 'flirty', 'What kind of touch helps you feel cherished?'),
  ('spicy', 'flirty', 'What outfit, scent, or detail of mine catches your attention?'),
  ('spicy', 'flirty', 'What is your favorite way for us to flirt during a normal day?'),
  ('spicy', 'flirty', 'What romantic scene should we recreate in our own style?'),
  ('spicy', 'flirty', 'What makes you feel wanted beyond words?'),
  ('spicy', 'flirty', 'What tiny gesture could make tonight feel more romantic?'),
  ('spicy', 'flirty', 'What is a sweet secret signal we could use in public?'),
  ('spicy', 'flirty', 'What memory of our chemistry still gives you butterflies?'),
  ('spicy', 'flirty', 'What would make our next kiss feel cinematic?')
on conflict (prompt) do nothing;
