import { CalendarHeart, MessageCircleHeart, Plus, Sparkles } from 'lucide-react';
import { Button, ButtonLink } from '@/components/button';
import { GameCard } from '@/components/game-card';
import { AppLogo, MobileCard } from '@/components/shell';
import { games } from '@/lib/games/catalog';
import { createClient } from '@/lib/supabase/server';

export default async function DashboardPage() {
  const supabase = await createClient();
  const {
    data: { user }
  } = await supabase.auth.getUser();

  const firstName = user?.email?.split('@')[0] ?? 'lovebirds';

  return (
    <main className="min-h-screen bg-romantic-radial px-5 py-5">
      <div className="mx-auto flex max-w-6xl items-center justify-between">
        <AppLogo />
        <form action="/auth/signout" method="post"><Button variant="secondary" type="submit">Sign out</Button></form>
      </div>
      <section className="mx-auto grid max-w-6xl gap-6 py-8 lg:grid-cols-[1fr_360px]">
        <div className="space-y-6">
          <MobileCard>
            <p className="text-sm font-bold uppercase tracking-[0.24em] text-rose-400">Your private dashboard</p>
            <h1 className="mt-3 text-4xl font-black text-plum">Hi, {firstName}. Ready to make tonight feel intentional?</h1>
            <p className="mt-3 max-w-2xl text-slate-600">Invite your partner, answer a prompt, choose a game, or save a new memory. Everything is designed mobile-first for quick check-ins and cozy date-night sessions.</p>
            <div className="mt-6 grid gap-3 sm:grid-cols-3">
              <Stat icon={MessageCircleHeart} label="Prompts" value="100" />
              <Stat icon={CalendarHeart} label="Date ideas" value="24" />
              <Stat icon={Sparkles} label="Active games" value="4" />
            </div>
          </MobileCard>
          <div className="grid gap-4 md:grid-cols-2">
            {games.map((game) => <GameCard key={game.slug} game={game} />)}
          </div>
        </div>
        <aside className="space-y-6">
          <MobileCard>
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-black text-plum">Couple setup</h2>
              <Plus className="size-5 text-rose-500" />
            </div>
            <ol className="mt-5 space-y-4 text-sm text-slate-600">
              <li className="rounded-3xl bg-white/70 p-4"><strong className="text-plum">1. Create a couple.</strong><br />Supabase stores one private row per relationship.</li>
              <li className="rounded-3xl bg-white/70 p-4"><strong className="text-plum">2. Invite your partner.</strong><br />Share an invitation code generated by the database.</li>
              <li className="rounded-3xl bg-white/70 p-4"><strong className="text-plum">3. Start a ritual.</strong><br />Play a question, memory, date, or award flow.</li>
            </ol>
          </MobileCard>
          <MobileCard>
            <h2 className="text-xl font-black text-plum">Tonight's shortcut</h2>
            <p className="mt-2 text-sm leading-6 text-slate-600">Start with the question jar and save your favorite answer to the memory lane timeline.</p>
            <ButtonLink href="/games/question-jar" className="mt-5 w-full">Draw a question</ButtonLink>
          </MobileCard>
        </aside>
      </section>
    </main>
  );
}

function Stat({ icon: Icon, label, value }: { icon: typeof MessageCircleHeart; label: string; value: string }) {
  return (
    <div className="rounded-3xl bg-white/70 p-4">
      <Icon className="size-5 text-rose-500" />
      <p className="mt-3 text-2xl font-black text-plum">{value}</p>
      <p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">{label}</p>
    </div>
  );
}
