-- OurStory themed expansion: push notifications, reactions, favorites, goals, and 240 new prompts.

alter type public.game_type add value if not exists 'intimacy_cards';
alter type public.game_type add value if not exists 'late_night_talks';
alter type public.game_type add value if not exists 'flirty_chaos';
alter type public.game_type add value if not exists 'future_us';

create table if not exists public.notification_settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  daily_question_reminder boolean not null default true,
  partner_answered boolean not null default true,
  new_memory_added boolean not null default true,
  new_date_idea_added boolean not null default true,
  streak_reminder boolean not null default true,
  reminder_time time not null default '20:00',
  timezone text not null default 'UTC',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.answer_reactions (
  id uuid primary key default gen_random_uuid(),
  answer_id uuid not null references public.answers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null check (reaction in ('❤️', '😳', '🥹', '🔥')),
  created_at timestamptz not null default now(),
  unique(answer_id, user_id, reaction)
);

create table if not exists public.favorite_answers (
  id uuid primary key default gen_random_uuid(),
  answer_id uuid not null references public.answers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(answer_id, user_id)
);

create table if not exists public.shared_goals (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null references public.couples(id) on delete cascade,
  title text not null,
  summary text not null,
  category text not null default 'future_us',
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

drop trigger if exists notification_settings_touch_updated_at on public.notification_settings;
create trigger notification_settings_touch_updated_at before update on public.notification_settings for each row execute function public.touch_updated_at();
drop trigger if exists push_subscriptions_touch_updated_at on public.push_subscriptions;
create trigger push_subscriptions_touch_updated_at before update on public.push_subscriptions for each row execute function public.touch_updated_at();

alter table public.notification_settings enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.answer_reactions enable row level security;
alter table public.favorite_answers enable row level security;
alter table public.shared_goals enable row level security;

drop policy if exists "Users can manage their notification settings" on public.notification_settings;
create policy "Users can manage their notification settings" on public.notification_settings for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "Users can manage their push subscriptions" on public.push_subscriptions;
create policy "Users can manage their push subscriptions" on public.push_subscriptions for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "Members can manage answer reactions" on public.answer_reactions;
create policy "Members can manage answer reactions" on public.answer_reactions for all to authenticated using (user_id = auth.uid() and exists (select 1 from public.answers a where a.id = answer_id and public.can_access_session(a.session_id))) with check (user_id = auth.uid() and exists (select 1 from public.answers a where a.id = answer_id and public.can_access_session(a.session_id)));
drop policy if exists "Members can manage favorite answers" on public.favorite_answers;
create policy "Members can manage favorite answers" on public.favorite_answers for all to authenticated using (user_id = auth.uid() and exists (select 1 from public.answers a where a.id = answer_id and public.can_access_session(a.session_id))) with check (user_id = auth.uid() and exists (select 1 from public.answers a where a.id = answer_id and public.can_access_session(a.session_id)));
drop policy if exists "Members can read shared goals" on public.shared_goals;
create policy "Members can read shared goals" on public.shared_goals for select to authenticated using (public.is_couple_member(couple_id));
drop policy if exists "Members can create shared goals" on public.shared_goals;
create policy "Members can create shared goals" on public.shared_goals for insert to authenticated with check (created_by = auth.uid() and public.is_couple_member(couple_id));

insert into public.questions (category, mood, prompt) values
  ('intimacy', 'intimate', 'What form of affection makes you feel chosen even on an ordinary day?'),
  ('intimacy', 'intimate', 'When do you most crave reassurance from me, and what words help?'),
  ('intimacy', 'intimate', 'What small romantic ritual would make you feel more connected to me?'),
  ('intimacy', 'intimate', 'What kind of compliment reaches the deepest part of you?'),
  ('intimacy', 'intimate', 'How can I make you feel emotionally safe when you are overwhelmed?'),
  ('intimacy', 'intimate', 'What is a vulnerable truth you want us to hold with more tenderness?'),
  ('intimacy', 'intimate', 'What moment between us made you feel irresistible?'),
  ('intimacy', 'intimate', 'Which part of our chemistry still surprises you in the best way?'),
  ('intimacy', 'intimate', 'What does being cherished look like in your daily life?'),
  ('intimacy', 'intimate', 'How do you like me to show affection when words are not enough?'),
  ('intimacy', 'intimate', 'What romantic preference of yours should I understand better?'),
  ('intimacy', 'intimate', 'When do you feel most seen by my attention?'),
  ('intimacy', 'intimate', 'What helps you relax into closeness after a stressful day?'),
  ('intimacy', 'intimate', 'What is one loving habit we should protect from busyness?'),
  ('intimacy', 'intimate', 'What do you want me to notice more often about your heart?'),
  ('intimacy', 'intimate', 'What touch feels most reassuring when you need comfort?'),
  ('intimacy', 'intimate', 'How can we make our goodbyes and hellos more intentional?'),
  ('intimacy', 'intimate', 'What is a private memory of us that still warms you?'),
  ('intimacy', 'intimate', 'What makes you feel emotionally desired, not just physically wanted?'),
  ('intimacy', 'intimate', 'Which shared ritual would make our nights feel softer?'),
  ('intimacy', 'intimate', 'What fear about love becomes smaller when you tell me?'),
  ('intimacy', 'intimate', 'What kind of attention makes you feel like my favorite person?'),
  ('intimacy', 'intimate', 'How do you know when our connection is at its strongest?'),
  ('intimacy', 'intimate', 'What do you want our affection to feel like in five years?'),
  ('intimacy', 'intimate', 'What is one romantic boundary that helps you feel respected?'),
  ('intimacy', 'intimate', 'What part of your tenderness do you wish I praised more?'),
  ('intimacy', 'intimate', 'What kind of date makes you feel emotionally close afterward?'),
  ('intimacy', 'intimate', 'When did you realize my love had become familiar in a good way?'),
  ('intimacy', 'intimate', 'What does intimacy mean to you beyond physical closeness?'),
  ('intimacy', 'intimate', 'How can I invite you into deeper conversation gently?'),
  ('intimacy', 'intimate', 'What is one hidden preference that would help me love you better?'),
  ('intimacy', 'intimate', 'What makes a kiss feel meaningful instead of automatic?'),
  ('intimacy', 'intimate', 'How do you want us to repair after missing each other emotionally?'),
  ('intimacy', 'intimate', 'What phrase from me would help you feel grounded?'),
  ('intimacy', 'intimate', 'What is the sweetest way I could surprise you this month?'),
  ('intimacy', 'intimate', 'What makes you feel protected without feeling controlled?'),
  ('intimacy', 'intimate', 'Which everyday moment could become more romantic with intention?'),
  ('intimacy', 'intimate', 'What part of your inner world feels ready to share more?'),
  ('intimacy', 'intimate', 'What kind of vulnerability from me makes you feel trusted?'),
  ('intimacy', 'intimate', 'How do you want to be loved when you are quiet?'),
  ('intimacy', 'intimate', 'What romantic detail do you remember that I might have forgotten?'),
  ('intimacy', 'intimate', 'What does being emotionally pursued look like for you?'),
  ('intimacy', 'intimate', 'How can we make our home feel more like a love story?'),
  ('intimacy', 'intimate', 'What is a reassurance you need even when everything is okay?'),
  ('intimacy', 'intimate', 'What do you find attractive about how I care for you?'),
  ('intimacy', 'intimate', 'When do you feel most proud to be loved by me?'),
  ('intimacy', 'intimate', 'What connection ritual would you want before we sleep?'),
  ('intimacy', 'intimate', 'What kind of playful affection makes you blush?'),
  ('intimacy', 'intimate', 'How can I make space for your softer feelings?'),
  ('intimacy', 'intimate', 'What is one intimate question you wish I asked more often?'),
  ('intimacy', 'intimate', 'What makes you feel safe enough to be fully honest?'),
  ('intimacy', 'intimate', 'Which version of me do you feel closest to?'),
  ('intimacy', 'intimate', 'What do you want our romance to never outgrow?'),
  ('intimacy', 'intimate', 'What kind of message from me would brighten a hard day?'),
  ('intimacy', 'intimate', 'How can we make affection feel less rushed?'),
  ('intimacy', 'intimate', 'What is one way I can honor your need for reassurance?'),
  ('intimacy', 'intimate', 'What makes you feel like we are on the same emotional team?'),
  ('intimacy', 'intimate', 'What romantic tradition should begin with us this season?'),
  ('intimacy', 'intimate', 'What do you want me to understand about your desire for closeness?'),
  ('intimacy', 'intimate', 'What is a tiny act of love that would mean a lot tonight?'),
  ('late-night', 'deep', 'What fear are you carrying that you wish felt less lonely?'),
  ('late-night', 'deep', 'What dream still feels too tender to say out loud often?'),
  ('late-night', 'deep', 'Which part of your past are you learning to treat with compassion?'),
  ('late-night', 'deep', 'What insecurity shows up when you feel disconnected from me?'),
  ('late-night', 'deep', 'How do you imagine love changing us over the next decade?'),
  ('late-night', 'deep', 'What does marriage mean to you beyond the ceremony?'),
  ('late-night', 'deep', 'What kind of parent or mentor do you hope to become?'),
  ('late-night', 'deep', 'Where do you feel spiritually curious, grounded, or uncertain?'),
  ('late-night', 'deep', 'What purpose keeps calling you even when life gets loud?'),
  ('late-night', 'deep', 'What growth in me have you quietly noticed?'),
  ('late-night', 'deep', 'What grief or disappointment shaped how you receive love?'),
  ('late-night', 'deep', 'What future responsibility do you want us to prepare for together?'),
  ('late-night', 'deep', 'Where do you need more grace from yourself right now?'),
  ('late-night', 'deep', 'What does a peaceful life look like when nobody is watching?'),
  ('late-night', 'deep', 'What question about our future feels important but scary?'),
  ('late-night', 'deep', 'What belief about love are you trying to unlearn?'),
  ('late-night', 'deep', 'How can we make room for both ambition and rest?'),
  ('late-night', 'deep', 'What part of your identity do you want me to know more deeply?'),
  ('late-night', 'deep', 'What does emotional maturity look like for us in conflict?'),
  ('late-night', 'deep', 'Where do you hope our family story feels different from the past?'),
  ('late-night', 'deep', 'What are you afraid success might cost you?'),
  ('late-night', 'deep', 'What does healing look like in your current season?'),
  ('late-night', 'deep', 'What promise do you want us to practice instead of just say?'),
  ('late-night', 'deep', 'How do you want us to handle seasons when desire or energy changes?'),
  ('late-night', 'deep', 'What do you need when the world feels too heavy?'),
  ('late-night', 'deep', 'What dream home feeling matters more than the actual house?'),
  ('late-night', 'deep', 'Where do you feel called to be braver?'),
  ('late-night', 'deep', 'What part of commitment feels beautiful to you?'),
  ('late-night', 'deep', 'What part of commitment feels intimidating?'),
  ('late-night', 'deep', 'How should we protect our relationship from resentment?'),
  ('late-night', 'deep', 'What do you hope our love teaches people close to us?'),
  ('late-night', 'deep', 'What does forgiveness require from you before it feels real?'),
  ('late-night', 'deep', 'Where do you need more patience from me?'),
  ('late-night', 'deep', 'How do you want us to navigate money with honesty and care?'),
  ('late-night', 'deep', 'What kind of legacy would make you proud?'),
  ('late-night', 'deep', 'What prayer, mantra, or intention fits our relationship right now?'),
  ('late-night', 'deep', 'What do you wish I understood about your quiet moments?'),
  ('late-night', 'deep', 'How can we tell when we are drifting before it becomes distance?'),
  ('late-night', 'deep', 'What do you want to build that is bigger than either of us?'),
  ('late-night', 'deep', 'What sacrifice are you willing to make for the life we want?'),
  ('late-night', 'deep', 'What sacrifice would be unhealthy for us to normalize?'),
  ('late-night', 'deep', 'Where are you learning to trust love more?'),
  ('late-night', 'deep', 'What future version of us do you feel protective of?'),
  ('late-night', 'deep', 'How do you want us to handle disappointment in each other?'),
  ('late-night', 'deep', 'What makes you feel emotionally homeless, and what brings you back?'),
  ('late-night', 'deep', 'What truth about your needs has become clearer lately?'),
  ('late-night', 'deep', 'What do you want our late nights to make space for?'),
  ('late-night', 'deep', 'How can I support your purpose without trying to manage it?'),
  ('late-night', 'deep', 'What do you hope we laugh about when we are older?'),
  ('late-night', 'deep', 'What family pattern are you determined to heal?'),
  ('late-night', 'deep', 'What kind of rest do you want us to learn together?'),
  ('late-night', 'deep', 'Where do you feel most hopeful about us?'),
  ('late-night', 'deep', 'What do you want our future children, students, or community to see in us?'),
  ('late-night', 'deep', 'How do you want to be comforted when you feel ashamed?'),
  ('late-night', 'deep', 'What does a sacred partnership mean to you?'),
  ('late-night', 'deep', 'Where are you afraid of being misunderstood?'),
  ('late-night', 'deep', 'What would make our next chapter feel intentional?'),
  ('late-night', 'deep', 'What wisdom did pain give you that you still value?'),
  ('late-night', 'deep', 'What question should we revisit every year?'),
  ('late-night', 'deep', 'What do you want us to choose, even when life gets complicated?'),
  ('chaos', 'playful', 'If we had to flirt using only grocery items, what would you choose?'),
  ('chaos', 'playful', 'What ridiculous outfit would secretly make me laugh and blush?'),
  ('chaos', 'playful', 'Which one of us would start a pillow fight and then deny it?'),
  ('chaos', 'playful', 'What is my most suspiciously adorable habit?'),
  ('chaos', 'playful', 'If our next kiss had a movie title, what would it be?'),
  ('chaos', 'playful', 'What silly dare would make date night instantly better?'),
  ('chaos', 'playful', 'Which of us would accidentally become mayor of a tiny island?'),
  ('chaos', 'playful', 'What snack best represents our chemistry?'),
  ('chaos', 'playful', 'If we swapped personalities for a day, what chaos happens first?'),
  ('chaos', 'playful', 'What is the most dramatic way to ask for cuddles?'),
  ('chaos', 'playful', 'Which inside joke deserves a national monument?'),
  ('chaos', 'playful', 'What flirty text would make you grin at the worst possible time?'),
  ('chaos', 'playful', 'Who would win a competition for best fake jealousy face?'),
  ('chaos', 'playful', 'What weird superpower would make me more attractive?'),
  ('chaos', 'playful', 'If our love language was a weather forecast, what would it say?'),
  ('chaos', 'playful', 'What harmless prank would you absolutely suspect me of doing?'),
  ('chaos', 'playful', 'Which one of us is more likely to overpack for a one-night getaway?'),
  ('chaos', 'playful', 'What fictional villain would secretly ship us?'),
  ('chaos', 'playful', 'What is the funniest place to dramatically confess love?'),
  ('chaos', 'playful', 'If we had a couple theme song for errands, what is the vibe?'),
  ('chaos', 'playful', 'What tiny habit of mine should be illegal because it is too cute?'),
  ('chaos', 'playful', 'Which one of us would survive a haunted bakery?'),
  ('chaos', 'playful', 'What would our couple mascot say as its catchphrase?'),
  ('chaos', 'playful', 'What is your most chaotic date idea that might still be amazing?'),
  ('chaos', 'playful', 'If I were a dessert, what would I be and why?'),
  ('chaos', 'playful', 'What would make a slow dance in the kitchen more ridiculous?'),
  ('chaos', 'playful', 'Which one of us would become emotionally attached to a vacation pigeon?'),
  ('chaos', 'playful', 'What fake scandal would our friends believe about us for five minutes?'),
  ('chaos', 'playful', 'What is the funniest compliment you can give me sincerely?'),
  ('chaos', 'playful', 'If we opened a romance detective agency, what case would we solve?'),
  ('chaos', 'playful', 'What is my most kissable but inconvenient trait?'),
  ('chaos', 'playful', 'Which one of us would lose a staring contest first?'),
  ('chaos', 'playful', 'What flirting technique should we retire immediately?'),
  ('chaos', 'playful', 'What flirting technique should we absolutely keep forever?'),
  ('chaos', 'playful', 'If our couch could talk, what would it expose?'),
  ('chaos', 'playful', 'What chaos snack would fuel our midnight adventure?'),
  ('chaos', 'playful', 'Which celebrity chef would judge our relationship meals?'),
  ('chaos', 'playful', 'What is the most unserious reason you would challenge me to a duel?'),
  ('chaos', 'playful', 'If I had a warning label, what would it say?'),
  ('chaos', 'playful', 'What tiny romantic gesture would make you act dramatically overwhelmed?'),
  ('chaos', 'playful', 'Which one of us has stronger “main character entering a room” energy?'),
  ('chaos', 'playful', 'What would our couple reality show be called?'),
  ('chaos', 'playful', 'What ridiculous trophy should we compete for tonight?'),
  ('chaos', 'playful', 'Which one of us would be worse at hiding a surprise?'),
  ('chaos', 'playful', 'What is your most chaotic but romantic travel plan?'),
  ('chaos', 'playful', 'What pet name is too powerful to use in public?'),
  ('chaos', 'playful', 'If our relationship were a board game, what is the wild card?'),
  ('chaos', 'playful', 'What is the funniest way to request attention?'),
  ('chaos', 'playful', 'Which one of us would accidentally turn a picnic into an expedition?'),
  ('chaos', 'playful', 'What flirty compliment sounds like a threat but is sweet?'),
  ('chaos', 'playful', 'What random object in this room has date-night potential?'),
  ('chaos', 'playful', 'Which one of us would become famous for a weird dance move?'),
  ('chaos', 'playful', 'What would our emergency romance protocol include?'),
  ('chaos', 'playful', 'What silly bet would make chores more fun?'),
  ('chaos', 'playful', 'If I had to win you over with one snack and one sentence, what works?'),
  ('chaos', 'playful', 'What would make you laugh during a romantic photoshoot?'),
  ('chaos', 'playful', 'Which one of us has more suspicious blanket-stealing energy?'),
  ('chaos', 'playful', 'What playful rule should exist for our next movie night?'),
  ('chaos', 'playful', 'What fake couple award would we definitely win?'),
  ('chaos', 'playful', 'What is the most chaotic way to say “I missed you”?'),
  ('future', 'vision', 'What does our dream home feel like when we walk through the door?'),
  ('future', 'vision', 'How should money support our values instead of controlling us?'),
  ('future', 'vision', 'What travel memory do you want future-us to be proud we made?'),
  ('future', 'vision', 'What does marriage look like in daily habits, not just promises?'),
  ('future', 'vision', 'How do you imagine children, chosen family, or mentorship in our life?'),
  ('future', 'vision', 'What business or creative project would be exciting to build together?'),
  ('future', 'vision', 'What lifestyle pace would help us stay healthy and in love?'),
  ('future', 'vision', 'What morning routine would future-us thank us for practicing?'),
  ('future', 'vision', 'What legacy do you want our relationship to leave?'),
  ('future', 'vision', 'What does retirement mean if we define it our own way?'),
  ('future', 'vision', 'Where should we be more aligned before making big commitments?'),
  ('future', 'vision', 'What kind of neighborhood or community would help us thrive?'),
  ('future', 'vision', 'How should we decide when to save, spend, or celebrate?'),
  ('future', 'vision', 'What annual tradition should future-us protect?'),
  ('future', 'vision', 'What does a strong partnership look like during career changes?'),
  ('future', 'vision', 'How much adventure do you want in our long-term life?'),
  ('future', 'vision', 'What kind of family culture do you want around holidays?'),
  ('future', 'vision', 'What is one skill we should learn for our future home?'),
  ('future', 'vision', 'How do you want us to handle aging with humor and tenderness?'),
  ('future', 'vision', 'What shared goal would make the next year feel meaningful?'),
  ('future', 'vision', 'Where do you want us to be more courageous financially?'),
  ('future', 'vision', 'What does “enough” look like for our lifestyle?'),
  ('future', 'vision', 'What dream should we not postpone forever?'),
  ('future', 'vision', 'How should we protect romance when routines get full?'),
  ('future', 'vision', 'What kind of hosts do you imagine us becoming?'),
  ('future', 'vision', 'What long-term health habit should we start gently?'),
  ('future', 'vision', 'How do you want us to divide responsibilities without scorekeeping?'),
  ('future', 'vision', 'What future purchase should reflect our values?'),
  ('future', 'vision', 'Where do you hope we travel slowly instead of rushing?'),
  ('future', 'vision', 'What does a family meeting look like in our home?'),
  ('future', 'vision', 'What shared cause or generosity practice matters to you?'),
  ('future', 'vision', 'How should we make decisions when our dreams differ?'),
  ('future', 'vision', 'What should our future bedroom feel like emotionally?'),
  ('future', 'vision', 'What do you want our weekends to protect?'),
  ('future', 'vision', 'How can we build a life that leaves room for surprise?'),
  ('future', 'vision', 'What milestone should we define differently than everyone else?'),
  ('future', 'vision', 'What does financial intimacy mean to you?'),
  ('future', 'vision', 'What future challenge should we prepare for as a team?'),
  ('future', 'vision', 'How do you imagine us celebrating ten years of choosing each other?'),
  ('future', 'vision', 'What does stability mean without becoming boring?'),
  ('future', 'vision', 'What shared learning goal belongs in our future?'),
  ('future', 'vision', 'Where do you want more simplicity in our life plan?'),
  ('future', 'vision', 'What big dream feels more possible because we are together?'),
  ('future', 'vision', 'How should we document our story for future-us?'),
  ('future', 'vision', 'What kind of elder couple do you hope we become?'),
  ('future', 'vision', 'What would our ideal work-life rhythm look like?'),
  ('future', 'vision', 'How do we want to make space for friends and solitude?'),
  ('future', 'vision', 'What future responsibility scares you but also matters?'),
  ('future', 'vision', 'What is one boundary that will protect our future family?'),
  ('future', 'vision', 'What long-term goal should be fun, not just productive?'),
  ('future', 'vision', 'How should we revisit our goals when life changes?'),
  ('future', 'vision', 'What does success look like if love stays central?'),
  ('future', 'vision', 'Where do we need a shared vision instead of assumptions?'),
  ('future', 'vision', 'What is one “someday” we could begin in a tiny way now?'),
  ('future', 'vision', 'How do you want our home to welcome rest?'),
  ('future', 'vision', 'What legacy story do you want people to tell about us?'),
  ('future', 'vision', 'What financial dream should we turn into a plan?'),
  ('future', 'vision', 'How should future-us handle seasons of caregiving?'),
  ('future', 'vision', 'What is a routine that would make our love feel steady?'),
  ('future', 'vision', 'What promise should guide the life we are building?')
on conflict (prompt) do nothing;
